name: Build
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: [srcpkgs/**]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, x86_64-musl]
    env:
      XBPS_TARGET_ARCH: ${{ matrix.arch }}
      XBPS_CHROOT_CMD: ethereal
      XBPS_ALLOW_CHROOT_BREAKOUT: yes
    steps:
      - name: get xbps static
        run: |
          curl -o /tmp/xbps.tar.xz -fLO https://repo-default.voidlinux.org/static/xbps-static-static-0.60.4_1.x86_64-musl.tar.xz
          sudo tar xvf /tmp/xbps.tar.xz -C / 
      - name: checkout voiders-community/packages
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: build ${{ matrix.arch }}
        run: |
          echo XBPS_CHROOT_CMD=ethereal >> ./void-packages/etc/conf
          echo XBPS_ALLOW_CHROOT_BREAKOUT=yes >> ./void-packages/etc/conf
          ln -s / void-packages/masterdir
          ./make bootstrap
          ./make build bibata-modern-ice
