name: Build
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: [srcpkgs/**]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-musl:
    runs-on: ubuntu-latest
    steps:
      - name: get xbps static
        run: |
          curl -o /tmp/xbps.tar.xz -fLO https://repo-default.voidlinux.org/static/xbps-static-static-0.60.4_1.x86_64-musl.tar.xz
          sudo tar xvf /tmp/xbps.tar.xz -C / 
      - name: checkout voiders-community/packages
        uses: actions/checkout@v6
        with:
          path: /repo
      - name: foo
        run: |
          ls -lha /repo
        
